mashr:
  service_account_email: '' # user@project.iam.gserviceaccount.com
  json_keyfile: '' # the keyfile must be in current working directory
  table_id:     ''
  dataset_id:   ''
  project_id:   ''
  # name the integration for bucket, instance and function name.
  # integration_name must match regex (?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)
  integration_name: ''
  # you can set the command that runs embulk here.
  # embulk_config.yml is the required name of the config file generated for embulk:
  embulk_run_command: 'embulk run embulk_config.yml' # 'embulk run embulk_config.yml -c embulk_diff.yml'
  embulk_gems:
    # - embulk-input-random
embulk: # read about embulk here: https://github.com/embulk/embulk
  # exec:
  #   min_output_tasks: 1
  # in:
  #   type: random
  #   rows: 10
  #   threads: 1
  #   schema:
  #     myid: primary_key
  #     name: string
  #     score: integer
