exec:
  min_output_tasks: 1
in:
  type: http
  url: https://jsonplaceholder.typicode.com/posts/42
  method: get
  parser:
    type: jsonpath
    columns:
        - { name: "json", type: string }
        - { name: "id", type: long }
        - { name: "title", type: string }
        - { name: "body", type: string }
out:
  type: gcs
  bucket: mashr
  path_prefix: my-bucket
  file_ext: .json
  auth_method: json_key
  service_account_email: ''
  json_keyfile: /root/mashr/keyfile.json
  formatter:
    type: jsonl
